2020-03-05 18:13:27,256 - root - INFO - Logger file successfully initialized
2020-03-05 18:14:17,610 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 44, in __init__
    self._transform_val_dir_like_train_dir_hierarchy()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 169, in _transform_val_dir_like_train_dir_hierarchy
    if len(image_files) != 0:
TypeError: object of type 'generator' has no len()
2020-03-05 18:23:36,508 - root - INFO - Logger file successfully initialized
2020-03-05 18:23:41,429 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 44, in __init__
    self._transform_val_dir_like_train_dir_hierarchy()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 178, in _transform_val_dir_like_train_dir_hierarchy
    for image_file_path in image_files:
  File "/usr/lib64/python3.6/pathlib.py", line 1098, in glob
    raise NotImplementedError("Non-relative patterns are unsupported")
NotImplementedError: Non-relative patterns are unsupported
2020-03-05 18:25:11,844 - root - INFO - Logger file successfully initialized
2020-03-05 18:25:16,607 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 44, in __init__
    self._transform_val_dir_like_train_dir_hierarchy()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 178, in _transform_val_dir_like_train_dir_hierarchy
    for image_file_path in image_files:
  File "/usr/lib64/python3.6/pathlib.py", line 1098, in glob
    raise NotImplementedError("Non-relative patterns are unsupported")
NotImplementedError: Non-relative patterns are unsupported
2020-03-05 18:25:48,199 - root - INFO - Logger file successfully initialized
2020-03-05 18:25:53,035 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 44, in __init__
    self._transform_val_dir_like_train_dir_hierarchy()
KeyboardInterrupt
2020-03-05 18:27:07,906 - root - INFO - Logger file successfully initialized
2020-03-05 18:27:12,832 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 44, in __init__
    self._transform_val_dir_like_train_dir_hierarchy()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 178, in _transform_val_dir_like_train_dir_hierarchy
    for image_file_path in image_files:
  File "/usr/lib64/python3.6/pathlib.py", line 1098, in glob
    raise NotImplementedError("Non-relative patterns are unsupported")
NotImplementedError: Non-relative patterns are unsupported
2020-03-05 18:27:27,477 - root - INFO - Logger file successfully initialized
2020-03-05 18:27:32,239 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 44, in __init__
    self._transform_val_dir_like_train_dir_hierarchy()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 178, in _transform_val_dir_like_train_dir_hierarchy
    for image_file_path in image_files:
  File "/usr/lib64/python3.6/pathlib.py", line 1098, in glob
    raise NotImplementedError("Non-relative patterns are unsupported")
NotImplementedError: Non-relative patterns are unsupported
2020-03-05 18:27:48,970 - root - INFO - Logger file successfully initialized
2020-03-05 18:27:53,644 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 44, in __init__
    self._transform_val_dir_like_train_dir_hierarchy()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 178, in _transform_val_dir_like_train_dir_hierarchy
    for image_file_path in image_files:
  File "/usr/lib64/python3.6/pathlib.py", line 1098, in glob
    raise NotImplementedError("Non-relative patterns are unsupported")
NotImplementedError: Non-relative patterns are unsupported
2020-03-05 18:28:14,931 - root - INFO - Logger file successfully initialized
2020-03-05 18:28:19,721 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 44, in __init__
    self._transform_val_dir_like_train_dir_hierarchy()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 178, in _transform_val_dir_like_train_dir_hierarchy
    for image_file_path in image_files:
KeyboardInterrupt
2020-03-05 18:32:14,151 - root - INFO - Logger file successfully initialized
2020-03-05 18:32:18,672 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 44, in __init__
    self._transform_val_dir_like_train_dir_hierarchy()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 168, in _transform_val_dir_like_train_dir_hierarchy
    image_files = glob.glob(self._val_data_dir.joinpath(r"/*.JPEG"))
AttributeError: 'function' object has no attribute 'glob'
2020-03-05 18:33:45,567 - root - INFO - Logger file successfully initialized
2020-03-05 18:33:50,152 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 44, in __init__
    self._transform_val_dir_like_train_dir_hierarchy()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 168, in _transform_val_dir_like_train_dir_hierarchy
    image_files = glob(self._val_data_dir.joinpath(r"/*.JPEG"))
  File "/usr/lib64/python3.6/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/lib64/python3.6/glob.py", line 41, in _iglob
    if not has_magic(pathname):
  File "/usr/lib64/python3.6/glob.py", line 149, in has_magic
    match = magic_check.search(s)
TypeError: expected string or bytes-like object
2020-03-05 18:34:56,003 - root - INFO - Logger file successfully initialized
2020-03-05 18:35:00,679 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 44, in __init__
    self._transform_val_dir_like_train_dir_hierarchy()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 179, in _transform_val_dir_like_train_dir_hierarchy
    image_name = os.path.basename(image_file_path.split('.')[0])
KeyboardInterrupt
2020-03-05 18:35:56,068 - root - INFO - Logger file successfully initialized
2020-03-05 18:35:58,783 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 44, in __init__
    self._transform_val_dir_like_train_dir_hierarchy()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 180, in _transform_val_dir_like_train_dir_hierarchy
    destination_dir = self._val_data_dir.joinpath(self.val_labels[image_name])
KeyError: 'ILSVRC2012_val_00015599'
2020-03-05 18:36:03,976 - root - INFO - Logger file successfully initialized
2020-03-05 18:36:08,721 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/data/p288722/softwares/pycharm-2019.3.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 44, in __init__
    self._transform_val_dir_like_train_dir_hierarchy()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 180, in _transform_val_dir_like_train_dir_hierarchy
    destination_dir = self._val_data_dir.joinpath(self.val_labels[image_name])
KeyError: 'ILSVRC2012_val_00015599'
2020-03-05 18:38:16,624 - root - INFO - Logger file successfully initialized
2020-03-05 18:38:19,577 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 43, in __init__
    self._extract_image_labels()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 77, in _extract_image_labels
    for file_name in file_names:
  File "/usr/lib64/python3.6/pathlib.py", line 1098, in glob
    raise NotImplementedError("Non-relative patterns are unsupported")
NotImplementedError: Non-relative patterns are unsupported
2020-03-05 18:38:40,802 - root - INFO - Logger file successfully initialized
2020-03-05 18:38:45,685 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 43, in __init__
    self._extract_image_labels()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 77, in _extract_image_labels
    for file_name in file_names:
KeyboardInterrupt
2020-03-05 18:43:00,231 - root - INFO - Logger file successfully initialized
2020-03-05 18:43:04,855 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 43, in __init__
    self._extract_image_labels()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 78, in _extract_image_labels
    root = ET.parse(file_name).getroot()
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
KeyboardInterrupt
2020-03-05 18:45:08,894 - root - INFO - Logger file successfully initialized
2020-03-05 18:45:11,894 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 43, in __init__
    self._extract_image_labels()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 78, in _extract_image_labels
    root = ET.parse(file_name).getroot()
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 608, in parse
    source.close()
KeyboardInterrupt
2020-03-05 18:49:50,872 - root - INFO - Logger file successfully initialized
2020-03-05 18:49:53,857 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 43, in __init__
    self._extract_image_labels()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 78, in _extract_image_labels
    root = ET.parse(file_name).getroot()
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
KeyboardInterrupt
2020-03-05 18:52:17,110 - root - INFO - Logger file successfully initialized
2020-03-05 18:52:20,147 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 43, in __init__
    self._extract_image_labels()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 78, in _extract_image_labels
    root = ET.parse(file_name).getroot()
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
KeyboardInterrupt
2020-03-05 18:58:30,756 - root - INFO - Logger file successfully initialized
2020-03-05 18:58:35,619 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 43, in __init__
    self._extract_image_labels()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 78, in _extract_image_labels
    root = ET.parse(file_name).getroot()
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 598, in parse
    return self._root
KeyboardInterrupt
2020-03-05 19:28:24,781 - root - INFO - Logger file successfully initialized
2020-03-05 19:28:29,603 - __main__ - INFO - Begin loading of ImageNet data
Traceback (most recent call last):
  File "/home/p288722/object-recognition/image-net-sota/run_flow.py", line 11, in <module>
    image_net_data = ImageNet()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 43, in __init__
    self._extract_image_labels()
  File "/home/p288722/object-recognition/image-net-sota/data/imagenet_object_localization_challenge.py", line 71, in _extract_image_labels
    train_file_names = glob(str(self._train_labels_dir) + r"/*/*")
  File "/usr/lib64/python3.6/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/lib64/python3.6/glob.py", line 73, in _iglob
    yield os.path.join(dirname, name)
  File "/usr/lib64/python3.6/posixpath.py", line 75, in join
    def join(a, *p):
KeyboardInterrupt
